# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pirestore.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pirestore.proto',
  package='pirestore',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fpirestore.proto\x12\tpirestore\"=\n\x08GreetMsg\x12\r\n\x05\x61lias\x18\x01 \x01(\t\x12\"\n\x06sender\x18\x02 \x01(\x0b\x32\x12.pirestore.Address\"f\n\x06SetReq\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07replica\x18\x03 \x01(\r\x12\x0e\n\x06origin\x18\x04 \x01(\x08\x12\x0f\n\x07visited\x18\x05 \x03(\t\x12\x0e\n\x06sender\x18\x06 \x01(\t\"&\n\x06GetReq\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07visited\x18\x02 \x03(\t\"5\n\x06ValReq\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\"G\n\x06RemReq\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07replica\x18\x02 \x01(\r\x12\x0f\n\x07visited\x18\x03 \x03(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\"\x19\n\x08GreetAck\x12\r\n\x05\x61lias\x18\x01 \x01(\t\"&\n\x06SetAck\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\r\x12\x0f\n\x07visited\x18\x02 \x03(\t\"9\n\x06GetAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07visited\x18\x03 \x03(\t\"(\n\x06ValAck\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\r\"&\n\x06RemAck\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\r\x12\x0f\n\x07visited\x18\x02 \x03(\t\"%\n\x07\x41\x64\x64ress\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r2\xac\x02\n\tPireStore\x12\x33\n\x05Greet\x12\x13.pirestore.GreetMsg\x1a\x13.pirestore.GreetAck\"\x00\x12.\n\x04ISet\x12\x11.pirestore.SetReq\x1a\x11.pirestore.SetAck\"\x00\x12-\n\x03Set\x12\x11.pirestore.SetReq\x1a\x11.pirestore.SetAck\"\x00\x12-\n\x03Get\x12\x11.pirestore.GetReq\x1a\x11.pirestore.GetAck\"\x00\x12-\n\x03Val\x12\x11.pirestore.ValReq\x1a\x11.pirestore.ValAck\"\x00\x12-\n\x03Rem\x12\x11.pirestore.RemReq\x1a\x11.pirestore.RemAck\"\x00\x62\x06proto3'
)




_GREETMSG = _descriptor.Descriptor(
  name='GreetMsg',
  full_name='pirestore.GreetMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alias', full_name='pirestore.GreetMsg.alias', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='pirestore.GreetMsg.sender', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=91,
)


_SETREQ = _descriptor.Descriptor(
  name='SetReq',
  full_name='pirestore.SetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pirestore.SetReq.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='pirestore.SetReq.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replica', full_name='pirestore.SetReq.replica', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='origin', full_name='pirestore.SetReq.origin', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visited', full_name='pirestore.SetReq.visited', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='pirestore.SetReq.sender', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=195,
)


_GETREQ = _descriptor.Descriptor(
  name='GetReq',
  full_name='pirestore.GetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pirestore.GetReq.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visited', full_name='pirestore.GetReq.visited', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=235,
)


_VALREQ = _descriptor.Descriptor(
  name='ValReq',
  full_name='pirestore.ValReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pirestore.ValReq.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='pirestore.ValReq.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='pirestore.ValReq.version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=290,
)


_REMREQ = _descriptor.Descriptor(
  name='RemReq',
  full_name='pirestore.RemReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pirestore.RemReq.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replica', full_name='pirestore.RemReq.replica', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visited', full_name='pirestore.RemReq.visited', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='pirestore.RemReq.sender', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=363,
)


_GREETACK = _descriptor.Descriptor(
  name='GreetAck',
  full_name='pirestore.GreetAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alias', full_name='pirestore.GreetAck.alias', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=390,
)


_SETACK = _descriptor.Descriptor(
  name='SetAck',
  full_name='pirestore.SetAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='pirestore.SetAck.ack', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visited', full_name='pirestore.SetAck.visited', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=430,
)


_GETACK = _descriptor.Descriptor(
  name='GetAck',
  full_name='pirestore.GetAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='pirestore.GetAck.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='pirestore.GetAck.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visited', full_name='pirestore.GetAck.visited', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=489,
)


_VALACK = _descriptor.Descriptor(
  name='ValAck',
  full_name='pirestore.ValAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='pirestore.ValAck.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='pirestore.ValAck.version', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=531,
)


_REMACK = _descriptor.Descriptor(
  name='RemAck',
  full_name='pirestore.RemAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='pirestore.RemAck.ack', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visited', full_name='pirestore.RemAck.visited', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=571,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='pirestore.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='pirestore.Address.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='pirestore.Address.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=610,
)

_GREETMSG.fields_by_name['sender'].message_type = _ADDRESS
DESCRIPTOR.message_types_by_name['GreetMsg'] = _GREETMSG
DESCRIPTOR.message_types_by_name['SetReq'] = _SETREQ
DESCRIPTOR.message_types_by_name['GetReq'] = _GETREQ
DESCRIPTOR.message_types_by_name['ValReq'] = _VALREQ
DESCRIPTOR.message_types_by_name['RemReq'] = _REMREQ
DESCRIPTOR.message_types_by_name['GreetAck'] = _GREETACK
DESCRIPTOR.message_types_by_name['SetAck'] = _SETACK
DESCRIPTOR.message_types_by_name['GetAck'] = _GETACK
DESCRIPTOR.message_types_by_name['ValAck'] = _VALACK
DESCRIPTOR.message_types_by_name['RemAck'] = _REMACK
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GreetMsg = _reflection.GeneratedProtocolMessageType('GreetMsg', (_message.Message,), {
  'DESCRIPTOR' : _GREETMSG,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.GreetMsg)
  })
_sym_db.RegisterMessage(GreetMsg)

SetReq = _reflection.GeneratedProtocolMessageType('SetReq', (_message.Message,), {
  'DESCRIPTOR' : _SETREQ,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.SetReq)
  })
_sym_db.RegisterMessage(SetReq)

GetReq = _reflection.GeneratedProtocolMessageType('GetReq', (_message.Message,), {
  'DESCRIPTOR' : _GETREQ,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.GetReq)
  })
_sym_db.RegisterMessage(GetReq)

ValReq = _reflection.GeneratedProtocolMessageType('ValReq', (_message.Message,), {
  'DESCRIPTOR' : _VALREQ,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.ValReq)
  })
_sym_db.RegisterMessage(ValReq)

RemReq = _reflection.GeneratedProtocolMessageType('RemReq', (_message.Message,), {
  'DESCRIPTOR' : _REMREQ,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.RemReq)
  })
_sym_db.RegisterMessage(RemReq)

GreetAck = _reflection.GeneratedProtocolMessageType('GreetAck', (_message.Message,), {
  'DESCRIPTOR' : _GREETACK,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.GreetAck)
  })
_sym_db.RegisterMessage(GreetAck)

SetAck = _reflection.GeneratedProtocolMessageType('SetAck', (_message.Message,), {
  'DESCRIPTOR' : _SETACK,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.SetAck)
  })
_sym_db.RegisterMessage(SetAck)

GetAck = _reflection.GeneratedProtocolMessageType('GetAck', (_message.Message,), {
  'DESCRIPTOR' : _GETACK,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.GetAck)
  })
_sym_db.RegisterMessage(GetAck)

ValAck = _reflection.GeneratedProtocolMessageType('ValAck', (_message.Message,), {
  'DESCRIPTOR' : _VALACK,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.ValAck)
  })
_sym_db.RegisterMessage(ValAck)

RemAck = _reflection.GeneratedProtocolMessageType('RemAck', (_message.Message,), {
  'DESCRIPTOR' : _REMACK,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.RemAck)
  })
_sym_db.RegisterMessage(RemAck)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'pirestore_pb2'
  # @@protoc_insertion_point(class_scope:pirestore.Address)
  })
_sym_db.RegisterMessage(Address)



_PIRESTORE = _descriptor.ServiceDescriptor(
  name='PireStore',
  full_name='pirestore.PireStore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=613,
  serialized_end=913,
  methods=[
  _descriptor.MethodDescriptor(
    name='Greet',
    full_name='pirestore.PireStore.Greet',
    index=0,
    containing_service=None,
    input_type=_GREETMSG,
    output_type=_GREETACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ISet',
    full_name='pirestore.PireStore.ISet',
    index=1,
    containing_service=None,
    input_type=_SETREQ,
    output_type=_SETACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Set',
    full_name='pirestore.PireStore.Set',
    index=2,
    containing_service=None,
    input_type=_SETREQ,
    output_type=_SETACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='pirestore.PireStore.Get',
    index=3,
    containing_service=None,
    input_type=_GETREQ,
    output_type=_GETACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Val',
    full_name='pirestore.PireStore.Val',
    index=4,
    containing_service=None,
    input_type=_VALREQ,
    output_type=_VALACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Rem',
    full_name='pirestore.PireStore.Rem',
    index=5,
    containing_service=None,
    input_type=_REMREQ,
    output_type=_REMACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PIRESTORE)

DESCRIPTOR.services_by_name['PireStore'] = _PIRESTORE

# @@protoc_insertion_point(module_scope)
